<!DOCTYPE html>
<html lang="en">
    <head>
        <title><?php echo $this->response->getData()['title'] ? $this->response->getData()['title'] : 'BlogPuro'; ?></title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" href="/public/favicon.ico">
        <link href="/public/vendors/bootstrapv3.3.1/css/bootstrap.min.css" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="/public/css/blog.css" rel="stylesheet">

        <!-- add stylesheets needed at runtime -->
        <?php echo $this->response->renderPartial('stylesheets'); ?>

        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <script type="text/javascript" src="/public/vendors/jquery-1.11.2.min.js"></script>
        <?php if($this->response->getIsActiveTinymce() === true): echo $this->response->renderPartial('tinymce-require-header'); endif; ?>
    </head>
    <body>
        <?php echo $this->response->renderPartial('header-nav'); ?>

        <div class="container-fluid">
            <div class="row">
                <?php echo $this->response->renderPartial('author-nav'); ?>
                <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                    <?php echo $this->response->renderPartial('operation-status'); ?>
                    <?php if(isset($this->response->getData()['controllerViewFolder'])): ?>
                        <?php echo $this->response->getView($this->response->getData()['controllerViewFolder']) ?>
                    <?php else: ?>
                        <?php echo $this->response->getView() ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <?php echo $this->response->renderPartial('footer'); ?>    

        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="/public/vendors/bootstrapv3.3.1/js/bootstrap.min.js"></script>
        <script src="/public/vendors/holder.js"></script>
    </body>

</html>