<!DOCTYPE html>
<html lang="en">
    <head>
        <title><?php echo $this->response->getData()['title'] ? $this->response->getData()['title'] : 'BlogPuro'; ?></title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" href="/public/favicon.ico">
        <link href="/public/vendors/bootstrapv3.3.1/css/bootstrap.min.css" rel="stylesheet">
        
        <!-- Custom styles for this template -->
        <link href="/public/css/blog.css" rel="stylesheet">
        
        <!-- add stylesheets needed at runtime -->
        <?php echo $this->response->renderPartial('stylesheets'); ?>
        
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <script type="text/javascript" src="/public/vendors/jquery-1.11.2.min.js"></script>

    </head>
    <body>
        <!-- @TODO: fare in modo che la response supporti l'inject dei partial
                    per rifattorizzare e spezzettare il layout in varie parti -->
        <?php echo $this->response->renderPartial('header'); ?>

        <div class="container">

            <?php echo $this->response->renderPartial('header-container'); ?>
        
            <div class="row" >
                <!-- main content here -->
                <div class="col-sm-8 blog-main">
                    
                    
                    
                    <?php echo $this->response->getView() ?>
                </div>
                <!-- sidebar -->
                <?php echo $this->response->renderPartial('sidebar'); ?>
            </div>
            
        </div>
        <?php echo $this->response->renderPartial('footer'); ?>    
            
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="/public/vendors/bootstrapv3.3.1/js/bootstrap.min.js"></script>
    </body>

</html>