<!DOCTYPE html>
<html>
    <head>
        <title><?php echo $this->response->getData()['title'] ? $this->response->getData()['title'] : 'BlogPuro'; ?></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" href="/public/favicon.ico">
    </head>
    <body>
        <?php echo $this->response->getView() ?>
    </body>
</html>