
<h1>Hi visitor! Welcome to BlogPuro ;) this is the homepage</h1>
<blockquote><?php echo $this->response->getData()['test']; ?></blockquote>
<br/>


<?php if( $this->response->getData()['posts'] ): ?>
<h2>Ultimi Post</h2>

<ul>
    <?php 
        foreach($this->response->getData()['posts'] as $post): ?>
    <li>
        <h3><?php echo $post->getTitle(); ?></h3>
        <p><?php echo $post->getMessage(); ?></p>
        <p><?php echo $post->getCreated(); ?></p>
    </li>
    <?php endforeach; ?>
</ul>

<?php endif; ?>
