<div class="row placeholders hidden-xs mini-dash">
    <div class="col-xs-6 col-sm-3 placeholder">
        <img data-src="holder.js/200x200/auto/sky" src="/public/images/github.jpg" class="img-responsive" alt="Generic placeholder thumbnail">
        <h4 class="text-crimson">GitHub</h4>
        <span class="text-muted"><a target="blank" href="https://github.com/">Get inspired</a></span>
    </div>
    <div class="col-xs-6 col-sm-3 placeholder">
        <img data-src="holder.js/200x200/auto/vine" src="/public/images/stackoverflow-2.png" class="img-responsive" alt="Generic placeholder thumbnail">
        <h4 class="text-crimson">Stackoverflow</h4>
        <span class="text-muted"><a target="blank" href="http://stackoverflow.com/">Questions to Answers</a></span>
    </div>
    <div class="col-xs-6 col-sm-3 placeholder">
        <img data-src="holder.js/200x200/auto/vine" src="/public/images/codeproject.jpg" class="img-responsive" alt="Generic placeholder thumbnail">
        <h4 class="text-crimson">Codeproject</h4>
        <span class="text-muted"><a target="blank" href="http://www.codeproject.com/">Free source code and tutorials</a></span>
    </div>
   
    <div class="col-xs-6 col-sm-3 placeholder">
        <img data-src="holder.js/200x200/auto/sky" src="/public/images/snipplr-2.jpg" class="img-responsive" alt="Generic placeholder thumbnail">
        <h4 class="text-crimson">Snipplr</h4>
        <span class="text-muted"><a target="blank" href="http://snipplr.com/">Code Snippets</a></span>
    </div>
     
    
</div>

