<div class="col-sm-3 col-sm-offset-1 blog-sidebar">
    <div class="sidebar-module">
        <div class="well">
            <p>Hi, <?php echo $this->getAuthService()->getUser()->getAuthorName(); ?>, welcome to <span class="text-black">Author <span class="text-crimson">Area</span></span></p>
        </div>
        <div class="list-group">
            <a href="#" class="list-group-item active">
              Dispay Your Posts
            </a>
            <a href="#" class="list-group-item">Write an article</a>
            <a href="#" class="list-group-item">Dispay Your Profile</a>
            <a href="#" class="list-group-item">Edit Your Profile's informations</a>
          </div>
    </div>
</div>
