<script type="text/javascript" src="/public/vendors/tinymce/tinymce.min.js"></script>
<script type="text/javascript">
tinymce.init({
    selector: "textarea",
    plugins: [
            "code advlist autolink link image print preview hr anchor pagebreak spellchecker",
         "searchreplace wordcount   code fullscreen insertdatetime nonbreaking",
         "save   directionality emoticons  paste textcolor"
        ],
        toolbar: "code undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | print preview media fullpage | forecolor backcolor emoticons"
 });
</script>

