<?php use \Justfun\Services\urlManagerService as  urlManagerService; ?>


<?php  if ($this->response->getData()['posts']): ?>
<h2 class="sub-header">Your BlogPosts</h2>    
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
          <tr>
            <th>ID</th>
            <th class="hidden-xs" >Title</th>
            <th>Url</th>
            <th class="hidden-xs">Created</th>
            <th>Published</th>
            <th>Comments</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
        </thead>
        <tbody>
           <?php foreach ($this->response->getData()['posts'] as $post):
                    
               ?>  
          <tr>
            <th scope="row"><?php echo $post->getId(); ?></th>
            <td class="hidden-xs"><?php echo $post->getTitle(); ?></td>
            <td><a href="<?php echo $post->getUrl();  ?>"> <?php echo $this->response->getUrlManager($post->getUrl(), urlManagerService::URL_SHOW,'post')->getUrl(); ?></a></td>
            <td class="hidden-xs"><?php echo $post->getCreated(); ?></td>
            <td class="centerTable"><?php echo $post->getPublished() == 1 ? 'Yes':'No'; ?></td>
            <td class="centerTable"> <?php echo $post->getCommentsCount(); ?> <span class="glyphicon glyphicon-comment" aria-hidden="true"></span></td>
            <td class="centerTable"><a href="/post/edit/<?php echo $post->getId(); ?>" ><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a></td>
            <td class="centerTable"><a href="/post/delete/<?php echo $post->getId(); ?>" > <span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a></td>
          </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
      <?php if(isset($this->response->getData()['paginator'])) echo $this->renderPartial('paginator','author'); ?>
</div>
<?php endif; ?>


<?php /* if ($this->response->getData()['posts']): ?>
    <?php foreach ($this->response->getData()['posts'] as $post): ?>
        <div class="blog-post">
            <h2 class="blog-post-title"><?php echo $post->getTitle(); ?></h2>
            <p class="blog-post-meta"><?php echo $post->getCreated(); ?> by  <a href="#"><?php echo $post->getUser()->getAuthorName(); ?></a></p>
            <p>
                <?php echo $post->getMessagePreview(); ?> 
                 <a href="<?php echo $post->getUrl(); ?>"> 
                     <small><span class="glyphicon glyphicon-link"></span> Read more</small> 
                </a> 
            </p>
            
        </div>
    <?php endforeach; ?>
    <?php echo $this->response->renderPartial('paginator','index'); ?>
<?php endif;*/ ?>

